FPS.MNTMgr.Web/Controllers/CommonController.cs
using System;
using System.Configuration;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using System.Threading;

using FPS.Applications.Extensions;

using FPS.MNTMgr.Web.Controllers.Base;
using FPS.MNTMgr.Web.Models;
using FPS.MNTMgr.Languages.Helpers;
using FPS.MNTMgr.Repositories;
using FPS.MNTMgr.Models;

namespace FPS.MNTMgr.Web.Controllers
{
    public class CommonController : MNTMgrDbController
    {
        public string SetCulture(string culture, string calendarlocalfile)
        {
            // Validate input
            culture = CultureHelper.GetImplementedCulture(culture);

            RouteData.Values["culture"] = culture;

            // Save culture in a cookie
            HttpCookie cultureCookie = Request.Cookies["_culture"];
            if (cultureCookie != null)
                cultureCookie.Value = culture;   // update cookie value
            else
            {

                cultureCookie = new HttpCookie("_culture");
                cultureCookie.Value = culture;
                cultureCookie.Expires = DateTime.Now.AddYears(1);
            }
            Response.Cookies.Add(cultureCookie);

            // Save calendar local file in a cookie
            HttpCookie calendarlocalfileCookie = Request.Cookies["_calendarlocalfile"];
            if (calendarlocalfileCookie != null)
                calendarlocalfileCookie.Value = calendarlocalfile;   // update cookie value
            else
            {

                calendarlocalfileCookie = new HttpCookie("_calendarlocalfile");
                calendarlocalfileCookie.Value = calendarlocalfile;
                calendarlocalfileCookie.Expires = DateTime.Now.AddYears(1);
            }
            Response.Cookies.Add(calendarlocalfileCookie);

            // Modify current thread's cultures           
            Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo(culture);
            Thread.CurrentThread.CurrentUICulture = Thread.CurrentThread.CurrentCulture;

            CultureInfo.DefaultThreadCurrentCulture = Thread.CurrentThread.CurrentCulture;
            CultureInfo.DefaultThreadCurrentUICulture = Thread.CurrentThread.CurrentCulture;

            return Resources.GetText(FPS.MNTMgr.Settings.AppSettings.Message.Success);
        }

        /// <summary>
        /// adding add a new area
        /// </summary>
        /// <param name="siteAreaId"></param>
        /// <param name="siteAreaDisplayName"></param>
        /// <param name="siteAreaDescription"></param>
        /// <returns></returns>
        public string AddNewSiteArea(string siteAreaId, string siteAreaDisplayName, string siteAreaDescription)
        {
            siteAreaId = siteAreaId.RemoveSpecialCharacters();

            if (!string.IsNullOrEmpty(siteAreaId))
            {

                if (string.IsNullOrEmpty(siteAreaDisplayName))
                {
                    siteAreaDisplayName = siteAreaId;
                }

                if (string.IsNullOrEmpty(siteAreaDescription))
                {
                    siteAreaDescription = siteAreaId;
                }

                FPS.MNTMgr.Services.DataAccess.CommDataAccess dataAccess = new Services.DataAccess.CommDataAccess(defaultConnectionStringSettings);

                return dataAccess.MtrSiteAreasInsert(FPS.MNTMgr.Settings.AppSettings.DefaultSiteId, siteAreaId, siteAreaDisplayName, siteAreaDescription);
            }
            else
            {
                return "Insufficient data. Please verify.";
            }
        }

        /// <summary>
        /// add a new skill
        /// </summary>
        /// <param name="mtrSkillId"></param>
        /// <param name="mtrSkillDisplayName"></param>
        /// <param name="mtrSkillDescription"></param>
        /// <returns></returns>
        public string AddNewMtrSkill(string mtrSkillId, string mtrSkillDisplayName, string mtrSkillDescription)
        {
            if (!string.IsNullOrEmpty(mtrSkillId))
            {

                if (string.IsNullOrEmpty(mtrSkillDisplayName))
                {
                    mtrSkillDisplayName = mtrSkillId;
                }

                if (string.IsNullOrEmpty(mtrSkillDescription))
                {
                    mtrSkillDescription = mtrSkillId;
                }

                FPS.MNTMgr.Services.DataAccess.CommDataAccess dataAccess = new Services.DataAccess.CommDataAccess(defaultConnectionStringSettings);

                return dataAccess.MtrSkillsInsert(FPS.MNTMgr.Settings.AppSettings.DefaultSiteId, mtrSkillId, mtrSkillDisplayName, mtrSkillDescription);
            }
            else
            {
                return "Insufficient data. Please verify.";
            }
        }

        /// <summary>
        /// add a new event
        /// </summary>
        /// <param name="mtrEventId"></param>
        /// <param name="mtrEventRequiredHours"></param>
        /// <param name="mtrEventDisplayName"></param>
        /// <param name="mtrEventDescription"></param>
        /// <param name="mtrEventRequiredSkills"></param>
        /// <returns></returns>
        public string AddNewMtrEvent(string mtrEventId, string mtrEventRequiredHours, string mtrEventDisplayName, string mtrEventDescription, string mtrEventRequiredSkills)
        {
            mtrEventId = mtrEventId.RemoveSpecialCharacters();

            if (!string.IsNullOrEmpty(mtrEventId) && !string.IsNullOrEmpty(mtrEventRequiredSkills))
            {

                if (string.IsNullOrEmpty(mtrEventDisplayName))
                {
                    mtrEventDisplayName = mtrEventId;
                }

                if (string.IsNullOrEmpty(mtrEventDescription))
                {
                    mtrEventDescription = mtrEventId;
                }

                if (string.IsNullOrEmpty(mtrEventRequiredHours))
                {
                    mtrEventRequiredHours = "4";
                }

                FPS.MNTMgr.Services.DataAccess.CommDataAccess dataAccess = new Services.DataAccess.CommDataAccess(defaultConnectionStringSettings);

                dataAccess.MtrEventsInsert(FPS.MNTMgr.Settings.AppSettings.DefaultSiteId, mtrEventId, mtrEventRequiredHours, mtrEventDisplayName, mtrEventDescription);


                List<string> skills = mtrEventRequiredSkills.Split(',').ToList();

                foreach (string skill in skills)
                {
                    if (!string.IsNullOrEmpty(skill.Trim()))
                    {
                        dataAccess.MtrEventSkillsInsert(FPS.MNTMgr.Settings.AppSettings.DefaultSiteId, mtrEventId, skill.Trim(), skill.Trim() + " on " + mtrEventId);
                    }
                }


                return FPS.MNTMgr.Settings.AppSettings.Message.Success;
            }
            else
            {
                return "Insufficient data. Please verify.";
            }
        }

        /// <summary>
        /// adding a new resource
        /// </summary>
        /// <param name="culture"></param>
        /// <param name="name"></param>
        /// <param name="value"></param>
        /// <returns></returns>
        public string AddNewSiteResource(string culture, string name, string value)
        {
            if (!string.IsNullOrEmpty(culture) && !string.IsNullOrEmpty(name) && !string.IsNullOrEmpty(value))
            {
                FPS.MNTMgr.Languages.Services.DataAccess.CommDataAccess dataAccess = new Languages.Services.DataAccess.CommDataAccess(defaultConnectionStringSettings);

                return dataAccess.AddLanguageSiteResource(FPS.MNTMgr.Settings.AppSettings.DefaultSiteId, culture, name, value);
            }
            else
            {
                return "Insufficient data. Please verify.";
            }
        }

        public string AddNewEngineer(string userId, string fullName, string displayName, string description, string skills)
        {
            userId = userId.RemoveSpecialCharacters();

            if (!string.IsNullOrEmpty(userId) && !string.IsNullOrEmpty(fullName) && !string.IsNullOrEmpty(displayName))
            {

                FPS.MNTMgr.Services.DataAccess.CommDataAccess dataAccess = new Services.DataAccess.CommDataAccess(defaultConnectionStringSettings);

                //first to add engineer
                dataAccess.MtrEngineersInsert(userId, fullName, displayName, description);

                //second to add site
                Site site = SiteRepository.Sites.Values.FirstOrDefault(x => x.Id == FPS.MNTMgr.Settings.AppSettings.DefaultSiteId);
                dataAccess.MtrSiteEngineersInsert(site.Id, userId, "A", "Default Value");

                //thrid to add skills, for now, default to all possible skills
                List<string> skillList = skills.Split(',').ToList();
                foreach (string skill in skillList)
                {
                    if (!string.IsNullOrEmpty(skill.Trim()))
                    {
                        dataAccess.MtrEngineerSkillsInsert(site.Id, userId, skill.Trim(), 10, "Default Value");
                    }
                }

                //forth, to reset the working hours
                for (int i = -10; i <= 30; i++)
                {
                    DateTime workDay = DateTime.Now.Date.AddDays(i);
                    double availableHours = 8;

                    if (workDay.DayOfWeek == DayOfWeek.Saturday || workDay.DayOfWeek == DayOfWeek.Sunday)
                    {
                        availableHours = 0;
                    }

                    dataAccess.MtrEngineerAvailHoursInsert(site.Id, userId, workDay, availableHours, "Default Value");
                }

                return FPS.MNTMgr.Settings.AppSettings.Message.Success;
            }
            else
            {
                return "Insufficient data. Please verify.";
            }
        }

FPS.MNTMgr.Web/Controllers/ConfigurationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FPS.MNTMgr.Web.Controllers
{
    public class ConfigurationController : Controller
    {
        // GET: Settings
        public ActionResult Index()
        {
            return View();
        }
    }
}

FPS.MNTMgr.Web/Views/Configuration/Partial/_SiteAreaList.cshtml
@using FPS.MNTMgr.Models
@using FPS.MNTMgr.Repositories

@{
    string urlAddNewSiteArea = Url.Action("AddNewSiteArea", "Common");
    Dictionary<string, SiteArea> areas = new Dictionary<string, SiteArea>();
    if (SiteRepository.Sites.ContainsKey(FPS.MNTMgr.Settings.AppSettings.DefaultSiteId))
    {
        areas = SiteRepository.Sites[FPS.MNTMgr.Settings.AppSettings.DefaultSiteId].SiteAreas;
    }
}

<div>
    <div>
        <form id="formNewSiteArea" class="well" style="margin-bottom:0px;">
            <table style="min-width:80%;">
                <thead>
                    <tr>
                        <th>@(FPS.MNTMgr.Web.Models.Resources.GetText("Site"))</th>
                        <th>@(FPS.MNTMgr.Web.Models.Resources.GetText("Area"))</th>
                        <th>@(FPS.MNTMgr.Web.Models.Resources.GetText("Area Display Name"))</th>
                        <th>@(FPS.MNTMgr.Web.Models.Resources.GetText("Area Description"))</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        foreach (SiteArea siteArea in areas.Values.OrderBy(x => x.DisplayName))
                        {
                            <tr>
                                <td>@(siteArea.Site.DisplayName)</td>
                                <td>@(siteArea.Id)</td>
                                <td>@(siteArea.DisplayName)</td>
                                <td>@(siteArea.Description)</td>
                                <td></td>
                            </tr>
                        }
                    }

                    <tr>
                        <td colspan="5"> &nbsp;</td>
                    </tr>
                    <tr>
                        <td colspan="5" style="background-color:#dddddd;">@(FPS.MNTMgr.Web.Models.Resources.GetText("Add/Overwrite"))</td>
                    </tr>
                    <tr>
                        <td colspan="5"> &nbsp;</td>
                    </tr>
                    <tr>
                        <td>@(FPS.MNTMgr.Settings.AppSettings.DefaultSiteId)</td>
                        <td><input type="text" name="siteAreaId" id="siteAreaId" /></td>
                        <td><input type="text" name="siteAreaDisplayName" id="siteAreaDisplayName" /></td>
                        <td><input type="text" name="siteAreaDescription" id="siteAreaDescription" /></td>
                        <td>
                            <button type="button" id="btnNewSiteAreaCancel" data-dismiss="modal" class="btn">@(FPS.MNTMgr.Web.Models.Resources.GetText("Cancel"))</button>
                            <button type="button" id="btnNewSiteAreaSave" data-dismiss="modal" class="btn btn-primary">@(FPS.MNTMgr.Web.Models.Resources.GetText("Add/Overwrite"))</button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    </div>
    <div>

    </div>
</div>



<script type="text/javascript">

    $('#btnNewSiteAreaCancel').click(function () {
        ClearFormNewSiteArea();
    });


    $('#btnNewSiteAreaSave').click(function () {


        var dataRow = {
            'siteAreaId': $('#siteAreaId').val(),
            'siteAreaDisplayName': $('#siteAreaDisplayName').val(),
            'siteAreaDescription': $('#siteAreaDescription').val(),
        }

        ClearFormNewSiteArea();

        $.ajax({
            type: 'POST',
            url: '@(urlAddNewSiteArea)',
            data: dataRow,
            success: function (response) {
                if (response == 'SUCCESS') {
                    alert('@(FPS.MNTMgr.Web.Models.Resources.GetText("Data Added/Updated"))');
                }
                else {
                    alert('@(FPS.MNTMgr.Web.Models.Resources.GetText("Insufficient data. Please verify."))');
                }
            }
        });
    });

    function ClearFormNewSiteArea() {
        $('#siteAreaId').val("");
        $('#siteAreaDisplayName').val("");
        $('#siteAreaDescription').val("");
    }


</script>

FPS.MNTMgr.Web/Views/Configuration/Partial/_SiteEventList.cshtml
@using FPS.MNTMgr.Models
@using FPS.MNTMgr.Repositories

@{
    string urlAddNewMtrEvent = Url.Action("AddNewMtrEvent", "Common");
    Dictionary<string, MtrSkill> siteSkills = new Dictionary<string, MtrSkill>();
    Dictionary<string, MtrEvent> events = new Dictionary<string, MtrEvent>();


    if (SiteRepository.Sites.ContainsKey(FPS.MNTMgr.Settings.AppSettings.DefaultSiteId))
    {
        events = SiteRepository.Sites[FPS.MNTMgr.Settings.AppSettings.DefaultSiteId].MtrEvents;
        siteSkills = SiteRepository.Sites[FPS.MNTMgr.Settings.AppSettings.DefaultSiteId].MtrSkills;
    }
}

<div>
    <div>
        <form id="formNewMtrEvent" class="well" style="margin-bottom:0px;">
            <table style="min-width:100%;">
                <thead>
                    <tr>
                        <th>@(FPS.MNTMgr.Web.Models.Resources.GetText("Site"))</th>
                        <th>@(FPS.MNTMgr.Web.Models.Resources.GetText("Event"))</th>
                        <th>@(FPS.MNTMgr.Web.Models.Resources.GetText("Required Hours"))</th>
                        <th>@(FPS.MNTMgr.Web.Models.Resources.GetText("Event Display Name"))</th>
                        <th>@(FPS.MNTMgr.Web.Models.Resources.GetText("Event Description"))</th>
                        <th>@(FPS.MNTMgr.Web.Models.Resources.GetText("Required Skills"))</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        foreach (MtrEvent mtrEvent in events.Values.OrderBy(x => x.DisplayName))
                        {
                            <tr>
                                <td>@(mtrEvent.Site.DisplayName)</td>
                                <td>@(mtrEvent.Id)</td>
                                <td>@(mtrEvent.RequiredMntHours)</td>
                                <td>@(mtrEvent.DisplayName)</td>
                                <td>@(mtrEvent.Description)</td>
                                <td>
                                    <ul>
                                        @foreach (MtrSkill skill in mtrEvent.RequiredMtrSkills.Values.OrderBy(x => x.DisplayName))
                                        {
                                            <li>@(skill.DisplayName)</li>
                                        }
                                    </ul>
                                </td>
                                <td></td>
                            </tr>
                        }
                    }

                    <tr>
                        <td colspan="7"> &nbsp;</td>
                    </tr>
                    <tr>
                        <td colspan="7" style="background-color:#dddddd;">@(FPS.MNTMgr.Web.Models.Resources.GetText("Add/Overwrite"))</td>
                    </tr>
                    <tr>
                        <td colspan="7"> &nbsp;</td>
                    </tr>
                    <tr>
                        <td>@(FPS.MNTMgr.Settings.AppSettings.DefaultSiteId)</td>
                        <td><input type="text" name="mtrEventId" id="mtrEventId" /></td>
                        <td><input type="number" name="mtrEventRequiredHours" id="mtrEventRequiredHours" /></td>
                        <td><input type="text" name="mtrEventDisplayName" id="mtrEventDisplayName" /></td>
                        <td><input type="text" name="mtrEventDescription" id="mtrEventDescription" /></td>
                        <td>
                            <ul id="mtrEventRequiredSkills">
                                @foreach (MtrSkill skill in siteSkills.Values.OrderBy(x => x.DisplayName))
                                {
                                    <li><input type="checkbox" name="mtrEventRequiredSkills" value="@(skill.Id)"> @(skill.DisplayName) </li>
                                }
                            </ul>

                        </td>
                    </tr>
                    <tr>
                        <td colspan="7" style="text-align:right;">
                            <button type="button" id="btnNewMtrEventCancel" data-dismiss="modal" class="btn">@(FPS.MNTMgr.Web.Models.Resources.GetText("Cancel"))</button>
                            <button type="button" id="btnNewMtrEventSave" data-dismiss="modal" class="btn btn-primary">@(FPS.MNTMgr.Web.Models.Resources.GetText("Add/Overwrite"))</button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    </div>
    <div>

    </div>
</div>



<script type="text/javascript">

    $('#btnNewMtrEventCancel').click(function () {
        ClearFormNewMtrEvent();
    });


    $('#btnNewMtrEventSave').click(function () {

        //debugger;

        var mtrEventRequiredSkillValues = [];
        $('#mtrEventRequiredSkills input:checked').each(function () {
            mtrEventRequiredSkillValues.push(this.value);
        });

        //alert(mtrEventRequiredSkillValues);

        var dataRow = {
            'mtrEventId': $('#mtrEventId').val(),
            'mtrEventRequiredHours': $('#mtrEventRequiredHours').val(),
            'mtrEventDisplayName': $('#mtrEventDisplayName').val(),
            'mtrEventDescription': $('#mtrEventDescription').val(),
            'mtrEventRequiredSkills': mtrEventRequiredSkillValues.join(),
        }

        //ClearFormNewMtrEvent();

        //alert(dataRow);

        $.ajax({
            type: 'POST',
            url: '@(urlAddNewMtrEvent)',
            data: dataRow,
            success: function (response) {
                if (response == 'SUCCESS') {
                    alert('@(FPS.MNTMgr.Web.Models.Resources.GetText("Data Added/Updated"))');
                }
                else {
                    alert('@(FPS.MNTMgr.Web.Models.Resources.GetText("Insufficient data. Please verify."))');
                }
            }
        });
    });

    function ClearFormNewMtrEvent() {
        $('#mtrEventId').val("");
        $('#mtrEventRequiredHours').val("");
        $('#mtrEventDisplayName').val("");
        $('#mtrEventDescription').val("");
    }


</script>

FPS.MNTMgr.Web/Views/Configuration/Partial/_SiteResrouceList.cshtml
@using FPS.MNTMgr.Models
@using FPS.MNTMgr.Languages.Models
@using FPS.MNTMgr.Languages.Repositories


@{
    HttpCookie cultureCookie = Request.Cookies["_culture"];

    string urlAddNewSiteResource = Url.Action("AddNewSiteResource", "Common");
}

<div>
    <form id="formNewSiteResource" class="well" style="margin-bottom:0px;">
        <input type="hidden" name="SiteResourceCulture" id="SiteResourceCulture" value="@cultureCookie.Value" />
        <table style="min-width:80%;">
            <thead>
                <tr>
                    <th>@(FPS.MNTMgr.Web.Models.Resources.GetText("Culture"))</th>
                    <th>@(FPS.MNTMgr.Web.Models.Resources.GetText("Original Value"))</th>
                    <th>@(FPS.MNTMgr.Web.Models.Resources.GetText("Translated Value"))</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @{
                    foreach (SiteResource siteResource in LanguageRepository.SiteResources.Where(x => x.SiteId == FPS.MNTMgr.Settings.AppSettings.DefaultSiteId && x.Culture.Equals(cultureCookie.Value, StringComparison.InvariantCultureIgnoreCase)).OrderBy(x => x.Name))
                    {
                        <tr>
                            <td>@(siteResource.Culture)</td>
                            <td>@(siteResource.Name)</td>
                            <td>@(siteResource.Value)</td>
                            <td></td>
                        </tr>
                    }
                }

                <tr>
                    <td colspan="4"> &nbsp;</td>
                </tr>
                <tr>
                    <td colspan="4" style="background-color:#dddddd;">@(FPS.MNTMgr.Web.Models.Resources.GetText("Add/Overwrite"))</td>
                </tr>
                <tr>
                    <td colspan="4"> &nbsp;</td>
                </tr>
                <tr>
                    <td>@cultureCookie.Value</td>
                    <td><input type="text" name="SiteResourceName" id="SiteResourceName" /></td>
                    <td><input type="text" name="SiteResourceValue" id="SiteResourceValue" /></td>
                    <td>
                        <button type="button" id="btnNewSiteResourceCancel" data-dismiss="modal" class="btn">@(FPS.MNTMgr.Web.Models.Resources.GetText("Cancel"))</button>
                        <button type="button" id="btnNewSiteResourceSave" data-dismiss="modal" class="btn btn-primary">@(FPS.MNTMgr.Web.Models.Resources.GetText("Add/Overwrite"))</button>
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
</div>



<script type="text/javascript">

    $('#btnNewSiteResourceCancel').click(function () {
        ClearFormNewSiteResource();
    });


    $('#btnNewSiteResourceSave').click(function () {


        var dataRow = {
            'Culture': $('#SiteResourceCulture').val(),
            'Name': $('#SiteResourceName').val(),
            'Value': $('#SiteResourceValue').val(),
        }

        ClearFormNewSiteResource();

        $.ajax({
            type: 'POST',
            url: '@(urlAddNewSiteResource)',
            data: dataRow,
            success: function (response) {
                if (response == 'SUCCESS') {
                    alert('@(FPS.MNTMgr.Web.Models.Resources.GetText("Data Added/Updated"))');
                }
                else {
                    alert('@(FPS.MNTMgr.Web.Models.Resources.GetText("Insufficient data. Please verify."))');
                }
            }
        });
    });

    function ClearFormNewSiteResource() {
        $('#SiteResourceName').val("");
        $('#SiteResourceValue').val("");
    }


</script>

FPS.MNTMgr.Web/Views/Configuration/Partial/_SiteSkillList.cshtml
@using FPS.MNTMgr.Models
@using FPS.MNTMgr.Repositories

@{
    string urlAddNewMtrSkill = Url.Action("AddNewMtrSkill", "Common");
    Dictionary<string, MtrSkill> skills = new Dictionary<string, MtrSkill>();
    if (SiteRepository.Sites.ContainsKey(FPS.MNTMgr.Settings.AppSettings.DefaultSiteId))
    {
        skills = SiteRepository.Sites[FPS.MNTMgr.Settings.AppSettings.DefaultSiteId].MtrSkills;
    }
}

<div>
    <div>
        <form id="formNewMtrSkill" class="well" style="margin-bottom:0px;">
            <table style="min-width:80%;">
                <thead>
                    <tr>
                        <th>@(FPS.MNTMgr.Web.Models.Resources.GetText("Site"))</th>
                        <th>@(FPS.MNTMgr.Web.Models.Resources.GetText("Skill"))</th>
                        <th>@(FPS.MNTMgr.Web.Models.Resources.GetText("Skill Display Name"))</th>
                        <th>@(FPS.MNTMgr.Web.Models.Resources.GetText("Skill Description"))</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        foreach (MtrSkill mtrSkill in skills.Values.OrderBy(x => x.DisplayName))
                        {
                            <tr>
                                <td>@(mtrSkill.Site.DisplayName)</td>
                                <td>@(mtrSkill.Id)</td>
                                <td>@(mtrSkill.DisplayName)</td>
                                <td>@(mtrSkill.Description)</td>
                                <td></td>
                            </tr>
                        }
                    }

                    <tr>
                        <td colspan="5"> &nbsp;</td>
                    </tr>
                    <tr>
                        <td colspan="5" style="background-color:#dddddd;">@(FPS.MNTMgr.Web.Models.Resources.GetText("Add/Overwrite"))</td>
                    </tr>
                    <tr>
                        <td colspan="5"> &nbsp;</td>
                    </tr>
                    <tr>
                        <td>@(FPS.MNTMgr.Settings.AppSettings.DefaultSiteId)</td>
                        <td><input type="text" name="mtrSkillId" id="mtrSkillId" /></td>
                        <td><input type="text" name="mtrSkillDisplayName" id="mtrSkillDisplayName" /></td>
                        <td><input type="text" name="mtrSkillDescription" id="mtrSkillDescription" /></td>
                        <td>
                            <button type="button" id="btnNewMtrSkillCancel" data-dismiss="modal" class="btn">@(FPS.MNTMgr.Web.Models.Resources.GetText("Cancel"))</button>
                            <button type="button" id="btnNewMtrSkillSave" data-dismiss="modal" class="btn btn-primary">@(FPS.MNTMgr.Web.Models.Resources.GetText("Add/Overwrite"))</button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    </div>
    <div>

    </div>
</div>



<script type="text/javascript">

    $('#btnNewMtrSkillCancel').click(function () {
        ClearFormNewMtrSkill();
    });


    $('#btnNewMtrSkillSave').click(function () {


        var dataRow = {
            'mtrSkillId': $('#mtrSkillId').val(),
            'mtrSkillDisplayName': $('#mtrSkillDisplayName').val(),
            'mtrSkillDescription': $('#mtrSkillDescription').val(),
        }

        ClearFormNewMtrSkill();

        $.ajax({
            type: 'POST',
            url: '@(urlAddNewMtrSkill)',
            data: dataRow,
            success: function (response) {
                if (response == 'SUCCESS') {
                    alert('@(FPS.MNTMgr.Web.Models.Resources.GetText("Data Added/Updated"))');
                }
                else {
                    alert('@(FPS.MNTMgr.Web.Models.Resources.GetText("Insufficient data. Please verify."))');
                }
            }
        });
    });

    function ClearFormNewMtrSkill() {
        $('#mtrSkillId').val("");
        $('#mtrSkillDisplayName').val("");
        $('#mtrSkillDescription').val("");
    }


</script>